[server]
headless = true
runOnSave = true
port = 8501
enableCORS = false

[theme]
base = "dark"
primaryColor = "#1a73e8"
backgroundColor = "#f5f7fa"
secondaryBackgroundColor = "#c3cfe2"
textColor = "#000000"
font = "sans serif"